services:
  nacos:
    image: nacos/nacos-server:v2.3.1
    container_name: nacos-server
    environment:
      - MODE=standalone
    ports:
      - "8848:8848"
      - "9848:9848"
      - "9849:9849"

  mysql:
    image: mysql:8.0
    container_name: mysql-server
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=concert_cloud
    ports:
      - "3306:3306"

  redis:
    image: redis:7-alpine
    container_name: redis-server
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: rabbitmq-server
    ports:
      - "5672:5672"
      - "15672:15672"

  promtail:
    image: grafana/promtail:2.9.2
    container_name: promtail-server
    volumes:
      - ./promtail-config.yaml:/etc/promtail/config.yml
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/containers:/var/lib/docker/containers
    depends_on:
      - loki

  loki:
    image: grafana/loki:2.9.2
    container_name: loki-server
    ports:
      - "3100:3100"
    volumes:
      - ./loki-config.yaml:/etc/loki/local-config.yaml

  grafana:
    image: grafana/grafana:latest
    container_name: grafana-server
    environment:
      - GF_USERS_DEFAULT_LANGUAGE=zh-Hans
    ports:
      - "3000:3000"
    depends_on:
      - loki

  skywalking-oap:
    image: apache/skywalking-oap-server:9.5.0
    container_name: skywalking-oap
    ports:
      - "11800:11800"
      - "12800:12800"
    environment:
      SW_STORAGE: h2

  skywalking-ui:
    image: apache/skywalking-ui:9.5.0
    container_name: skywalking-ui
    ports:
      - "9080:8080"
    environment:
      SW_OAP_ADDRESS: http://skywalking-oap:12800
    depends_on:
      - skywalking-oap